### ISSUE TITLE
Hand history not displayed for turn, or river cards. 

### ISSUE THREAD

**Issue by aelkman** [hippich/Bitcoin-Poker-Room#87] opened 2011-07-19 07:33 UTC
Hand history does not show turn or river cards, effectively making it very hard to decipher the final hand. I am aware that it shows the made hands at the end which is fine, but it would be very helpful to also see turn and river cards or final cards dealt on the board somewhere.

**Comment by hippich** [comment] 2011-07-19 12:42
Duplicate of #86

**Closed as completed by hippich** 2011-07-19 12:42 UTC
