### ISSUE TITLE
Session instance has no attribute 'avatar'

### ISSUE THREAD

**Issue by hippich** [hippich/Bitcoin-Poker-Room#54] opened 2011-06-21 12:44 UTC
I've watched plenty with Chrome and haven't had any problems.
But there seems to be a problem joining a table at the moment, heres the message:

Lost connection to the poker server. Click to retry.
{"xhr":"{\"status\":500,\"responseText\":\"Traceback (most recent call last):\n  File \\"/usr/lib/python2.6/dist-packages/twisted/internet/base.py\\", line 778, in runUntilCurrent\n    call.func(_call.args, *_call.kw)\n  File \\"/usr/lib/python2.6/dist-packages/pokernetwork/pokeravatar.py\\", line 381, in longPollDeferredTimeout\n    d.callback(packets)\n  File \\"/usr/lib/python2.6/dist-packages/twisted/internet/defer.py\\", line 280, in callback\n    self._startRunCallbacks(result)\n  File \\"/usr/lib/python2.6/dist-packages/twisted/internet/defer.py\\", line 354, in _startRunCallbacks\n    self._runCallbacks()\n---  ---\n  File \\"/usr/lib/python2.6/dist-packages/twisted/internet/defer.py\\", line 371, in _runCallbacks\n    self.result = callback(self.result, _args, *_kw)\n  File \\"/usr/lib/python2.6/dist-packages/pokernetwork/pokersite.py\\", line 255, in render\n    session.site.updateSession(session)\n  File \\"/usr/lib/python2.6/dist-packages/pokernetwork/pokersite.py\\", line 483, in updateSession\n    serial = session.avatar.getSerial()\nexceptions.AttributeError: Session instance has no attribute 'avatar'\n\",\"readyState\":4}","status":"error","url":"/POKER_REST","error":"Internal Server Error"}attempt to stringify failed with exception: ReferenceError: printStackTrace is not defined

**Comment by anisoptera** [comment] 2011-06-24 20:19
Duplicate of #60.

**Closed as completed by anisoptera** 2011-06-24 20:19 UTC
