### ISSUE TITLE
Rebuy Button

### ISSUE THREAD

**Issue by GO1111** [hippich/Bitcoin-Poker-Room#106] opened 2011-07-30 15:55 UTC
Rebuy button disappears and only becomes available when you have money in the pot. You cannot reload until you actually play another hand. Very annoying

**Comment by hippich** [comment] 2011-08-16 23:41
Should be fixed with delays issue fixed. Feel free to re-open if it continue to happen.

**Closed as completed by hippich** 2011-08-16 23:41 UTC

**Comment by hippich** [comment] 2011-08-17 00:41
This project is not about getting around US legal issues. It is for people who interested in bitcoin technology and poker. Sorry about that, but this is problem with US government, not with this particular site. =)  

Making "proxy" or try to avoid it somehow differently only cause problems for me and players who believe into it as a way to avoid legal issues with their government and then get hooked just like FTP players got hooked when US gov. busted 'em.

It might work this way through TOR or I2P, but last time I checked, latency caused by these networks makes it impossible to play. It might changed - I need to look again. If this changed someone can take this project to new level - setup anonymous poker room in TOR or I2P and I will totally welcome it!

Anyway, this is off-topic in this particular ticket, feel free to join IRC chat (link in the bottom of the website) to discuss this further =)
